# Generated by Django 5.0.3 on 2024-06-18 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noteapp', '0002_remove_about_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='about',
            name='title',
        ),
        migrations.AddField(
            model_name='notes',
            name='title',
            field=models.CharField(default='Untitled', max_length=60),
        ),
    ]
