# Generated by Django 5.0.3 on 2024-06-19 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noteapp', '0004_notes_subject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notes',
            name='about',
            field=models.CharField(default='New notes, hope it helps :)', max_length=130),
        ),
        migrations.DeleteModel(
            name='About',
        ),
    ]
